#!/bin/sh
### BEGIN INIT INFO
# Provides:       stepper
# Required-Start: $syslog
# Required-Stop:  $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    Stepper motor initailizer
### END INIT INFO
log_daemon_msg "Initializing Stepper"
python /home/pi/work/syringePump
